services:
  notebook:
    image: quay.io/jupyter/minimal-notebook:latest
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/home/jovyan/work:cached
    # env_file:
    #   - ./notebook/.env
    #   - ./notebook/.env.dev
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=easy
      - CHOWN_EXTRA=/home/jovyan/work
      - CHOWN_EXTRA_OPTS=-R
    user: root
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=P@ssw0rd!
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-local=scram-sha-256 --auth-host=scram-sha-256
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  data_loader:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./data_loader/Dockerfile
    environment:
      - FILE_URL=https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2019-10.parquet
      - FILE_TAXI_ZONES_URL=https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv
      - DB_TABLE_NAME=green_tripdata_2019_10
      - DB_TAXI_ZONES_TABLE_NAME=taxi_zones
      - DB_NAME=ny_taxi
      - DB_HOST_NAME=db
      - DB_PORT=5432
      - DB_USER_NAME=postgres
      - DB_PASSWORD=P@ssw0rd!
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=P@ssw0rd!

volumes:
  db_data:
